### ISSUE TITLE
typo in plite vg help

### ISSUE THREAD

**Issue by RGunning** [njgit/App-Pipeline-Lite#11]
plite vg
    
    Usage: plite vc (view pipeline graph) [OPTIONS] PIPELINE_DIR
        -e --editor     Sets the editor e.g. plite vp -e vim. Overrides config file setting if exists.

**Comment by nw11** [comment]
fixed in https://github.com/njgit/App-Pipeline-Lite/commit/cd7bef5d5cde9afee08bc2d860c0ed358a2baaff
