### ISSUE TITLE
Issue with .groupby command

### ISSUE THREAD

**Issue by RGunning** [njgit/App-Pipeline-Lite#4]
plite is not reading stepname properly. It is combining the step with the meta of the previous step

it sees this:

    macsunmerged. 
        ...
    macsunmerged.cores 5

    wigCorrelate.groupby.replicate
        . /nfs/users/nfs_r/rg12/.bashrc;
        trap SomeErrorHandler ERR;
        ls [% wigCorrelate.groupby.replicate.macsunmerged.output16 %];

and tells me 

    macsunmerged:
        cmd: "cd /lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/output/run6/job0/macsunmerged; rm -r *;. /nfs/users/nfs_r/rg12/.bashrc;\ntrap SomeErrorHandler ERR;\nif [ PE == \"PE\" ]; then paired=\"BAMPE\";else paired=\"BAM\";fi;\nmacs2 callpeak -t /lustre/scratch110/sa$
        condition: ~
        cores: "5\nwigCorrelate.groupby.replicate\n. /nfs/users/nfs_r/rg12/.bashrc;\ntrap SomeErrorHandler ERR;\nls [% wigCorrelate.groupby.replicate.macsunmerged.output16 %];"
        dependents: []

**Comment by njgit** [comment]
Thanks, changes should now allow this syntax https://github.com/njgit/App-Pipeline-Lite/commit/3b336eb0e0cf26015f207a005f9200f134efece6
